on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: 

name: Tests with cache action
jobs:
  tests:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-size-5gb
      - nscloud-cache-tag-gha-demo-remix
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup npm cache
        uses: namespacelabs/nscloud-cache-action@e68bcb0b272eeb498b68dfbaf053f67a66389a0d
        with:
          path: |
            ~/.npm
            ./node_modules
          key: Linux-npm
          use-cache-volume: false

      - name: Install dependencies
        run: npm install

      - name: NPM tests
        run: npm run test
    
