on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: 

name: Tests
jobs:
  tests:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-size-5gb
      - nscloud-cache-tag-gha-demo-remix
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup npm cache
        uses: namespacelabs/nscloud-cache-action@a94f53552973f97728f59bb656f6a1106ec2e579
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-npm
          use-cache-volume: true

      - name: Install dependencies
        run: npm install

      - name: NPM tests
        run: npm run test
    
